### ISSUE TITLE
error: Bad Substitution

### ISSUE THREAD

**Issue by dbunt1tled** [Fowlron/dotfiles#1]
Script `wallpaper/wallpaper_timer` line 10 the error "Bad Substitution" was displayed, corrected by replacing 
`script_name=${BASH_SOURCE[0]}`
 with
`script_name=$0`

Debian 10.

**Comment by pedrofgodinho** [comment]
`$(BASH_SOURCE[0])` is a bash specific. On debian, `/bin/sh` is a symlink to `/bin/dash` and not `/bin/bash`. I will switch the shebang to `#!/bin/bash` to avoid this error in the future. Substituting it for `$0` _kinda_ works but might fail in some specific scenarios. See [here](https://stackoverflow.com/questions/35006457/choosing-between-0-and-bash-source).
